2021-02-05 15:48:28,676 ERROR: Exception on /explore [GET] [in c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\microblog\app\routes.py", line 48, in explore
    return render_template('index.html', title='Explore', posts=posts, next_url=next_url, prev_url=prev_url)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\Desktop\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\Desktop\microblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock content %}
  File "C:\Users\User\Desktop\microblog\app\templates\index.html", line 19, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2021-02-05 15:49:28,015 ERROR: Exception on /explore [GET] [in c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\microblog\app\routes.py", line 48, in explore
    return render_template('index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\Desktop\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\Desktop\microblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock content %}
  File "C:\Users\User\Desktop\microblog\app\templates\index.html", line 19, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2021-02-05 15:49:29,577 ERROR: Exception on /explore [GET] [in c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\User\Desktop\microblog\app\routes.py", line 48, in explore
    return render_template('index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\Desktop\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\Desktop\microblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock content %}
  File "C:\Users\User\Desktop\microblog\app\templates\index.html", line 19, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2021-02-05 15:49:33,414 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:45]
2021-02-05 15:49:42,145 ERROR: Exception on /index [POST] [in c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\User\Desktop\microblog\app\routes.py", line 21, in index
    post = Post(body=form.post.data, author=current_user)
  File "<string>", line 4, in __init__
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\sqlalchemy\orm\state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\sqlalchemy\orm\state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "c:\users\user\desktop\microblog\myenv\lib\site-packages\sqlalchemy\ext\declarative\base.py", line 840, in _declarative_constructor
    "%r is an invalid keyword argument for %s" % (k, cls_.__name__)
TypeError: 'body' is an invalid keyword argument for Post
2021-02-05 15:51:53,386 INFO: Microblog startup [in C:\Users\User\Desktop\microblog\app\__init__.py:45]
